resilience4j:
  retry:
    instances:
      retryApi:
        max-attempts: 5
        wait-duration: 5s
    metrics:
      legacy:
        enabled: true
      enaabled: true
  ratelimiter:
    instances:
      myRatelimiter:
        register-health-indicator: true
        limit-for-period: 5
        limit-refresh-period: 60s
        timeout-duration: 0s
        allow-health-indicator-to-fail: true
        subscribe-for-events: true
        event-consumer-buffer-size: 50
    metrics:
      enabled: true